# .github/workflows/main.yml
name: CI-ML-Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : récupérer le code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Étape 2 : installer Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Étape 3 : installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader stopwords punkt wordnet

      # Étape 4 : exécuter tout le pipeline dans un seul step
      - name: Run Data, Train and Evaluate
        run: |
          python src/load_data.py
          python src/preprocess.py
          python src/train.py
          python src/evaluate.py

      # Étape 5 : sauvegarder les modèles et MLflow comme artefact
      - name: Upload MLflow results and models
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: |
            mlruns/
            models/
